export type ComponentInfo = {
  path: string;
  name: string;
  description: string;
  dependencies: string[];
  exports: string[];
  props: ComponentPropInfo[];
};

const allSchemes = [
  "primary",
  "secondary",
  "tertiary",
  "neutral",
  "muted",
  "good",
  "caution",
  "bad",
];

export type ComponentPropInfo = {
  label: string;
  prop: string;
  description: string;
} & (
  | {
      type: "select";
      defaultValue?: string;
      options: string[];
    }
  | {
      type: "toggle-group";
      defaultValue?: string;
      options: string[];
    }
  | { type: "boolean"; defaultValue?: boolean }
  | { type: "string"; defaultValue?: string }
  | { type: "number"; defaultValue?: number }
);

export const componentInformation: ComponentInfo[] = [
  {
    path: "accordion",
    name: "Accordion",
    description: "An accordion component",
    dependencies: [
      "react",
      "class-variance-authority",
      "react-aria-components",
      "@/utils/cn",
    ],
    exports: [
      "Accordion",
      "AccordionItem",
      "AccordionTrigger",
      "AccordionContent",
    ],
    props: [],
  },
  {
    path: "chip",
    name: "Chip",
    description: "A chip component",
    dependencies: ["react", "class-variance-authority", "@/utils/cn"],
    exports: ["Chip"],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper"],
        defaultValue: "paper",
        description: "The material of the Chip",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: allSchemes,
        defaultValue: "primary",
        description: "The color scheme of the chip",
      },
    ],
  },
  {
    path: "breadcrumbs",
    name: "Breadcrumbs",
    description: "A breadcrumbs component",
    dependencies: [
      "react",
      "class-variance-authority",
      "react-aria-components",
      "@/utils/cn",
    ],
    exports: ["Breadcrumbs", "Breadcrumb"],
    props: [],
  },
  {
    path: "button",
    name: "Button",
    description: "A button component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-slot",
      "@/utils/cn",
    ],
    exports: ["Button"],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper", "outline", "ghost"],
        defaultValue: "paper",
        description: "The material of the button",
      },
      {
        prop: "aria-pressed",
        label: "Selected",
        type: "boolean",
        description: "The toggle-grouped state of the button",
      },
      {
        prop: "disabled",
        label: "Disabled",
        type: "boolean",
        description: "Whether the button is disabled",
      },
      {
        prop: "size",
        label: "Size",
        type: "toggle-group",
        options: ["sm", "md", "lg"],
        defaultValue: "md",
        description: "The size of the button",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: allSchemes,
        defaultValue: "primary",
        description: "The color scheme of the button",
      },
      {
        prop: "shape",
        label: "Shape",
        type: "toggle-group",
        options: ["pill", "icon"],
        defaultValue: "pill",
        description: "The shape of the button",
      },
    ],
  },
  {
    path: "dialog",
    name: "Dialog",
    description: "A dialog component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@/utils/cn",
      "@radix-ui/react-dialog",
    ],
    exports: [
      "Dialog",
      "DialogTrigger",
      "DialogContent",
      "DialogHeader",
      "DialogFooter",
      "DialogTitle",
      "DialogDescription",
      "DialogClose",
      "DialogExitButton",
      "DialogForm",
      "DialogOverlay",
      "DialogPortal",
    ],
    props: [
      {
        prop: "modal",
        label: "Modal",
        type: "boolean",
        defaultValue: true,
        description: "Whether the dialog is modal",
      },
    ],
  },
  {
    path: "drawer",
    name: "Drawer",
    description: "A drawer component",
    dependencies: ["react", "class-variance-authority", "@/utils/cn", "vaul"],
    exports: [
      "Drawer",
      "DrawerTrigger",
      "DrawerContent",
      "DrawerHeader",
      "DrawerFooter",
      "DrawerTitle",
      "DrawerDescription",
      "DrawerClose",
      "DrawerOverlay",
      "DrawerPortal",
    ],
    props: [
      {
        prop: "modal",
        label: "Modal",
        type: "boolean",
        defaultValue: true,
        description: "Whether the drawer is modal",
      },
      {
        prop: "position",
        label: "Position",
        type: "toggle-group",
        options: ["left", "right", "top", "bottom"],
        defaultValue: "bottom",
        description: "The position of the drawer",
      },
    ],
  },
  {
    path: "input",
    name: "Input",
    description: "An input component",
    dependencies: ["react", "class-variance-authority", "@/utils/cn"],
    exports: ["Input"],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper", "outline"],
        defaultValue: "outline",
        description: "The material of the input",
      },
      {
        prop: "size",
        label: "Size",
        type: "toggle-group",
        options: ["sm", "md", "lg"],
        defaultValue: "md",
        description: "The size of the input",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", ...allSchemes],
        defaultValue: "default",
        description: "The color scheme of the input",
      },
      {
        prop: "disabled",
        label: "Disabled",
        type: "boolean",
        description: "Whether the input is disabled",
      },
    ],
  },
  {
    path: "textarea",
    name: "Textarea",
    description: "A textarea component",
    dependencies: ["react", "class-variance-authority", "@/utils/cn"],
    exports: ["Textarea"],
    props: [
      {
        prop: "size",
        label: "Size",
        type: "toggle-group",
        options: ["sm", "md", "lg"],
        defaultValue: "md",
        description: "The size of the textarea",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: allSchemes,
        defaultValue: "primary",
        description: "The color scheme of the input",
      },
    ],
  },
  {
    path: "popover",
    name: "Popover",
    description: "A popover component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-popover",
      "@/utils/cn",
    ],
    exports: ["Popover", "PopoverTrigger", "PopoverContent", "PopoverArrow"],
    props: [],
  },
  {
    path: "separator",
    name: "Separator",
    description: "A separator component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-separator",
      "@/utils/cn",
    ],
    exports: ["Separator"],
    props: [
      {
        prop: "orientation",
        label: "Orientation",
        type: "toggle-group",
        options: ["horizontal", "vertical"],
        defaultValue: "horizontal",
        description: "The orientation of the separator",
      },
    ],
  },
  {
    path: "select",
    name: "Select",
    description: "A select component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-select",
      "@/utils/cn",
    ],
    exports: [
      "Select",
      "SelectTrigger",
      "SelectValue",
      "SelectContent",
      "SelectItem",
    ],
    props: [],
  },
  {
    path: "slider",
    name: "Slider",
    description: "A slider component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-slider",
      "@/utils/cn",
    ],
    exports: ["Slider"],
    props: [],
  },
  {
    path: "surface",
    name: "Surface",
    description: "A surface component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-slot",
      "@/utils/cn",
    ],
    exports: ["Surface"],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper", "glass"],
        defaultValue: "glass",
        description: "The material of the surface",
      },
      {
        prop: "interactive",
        label: "Interactive",
        type: "boolean",
        description: "Whether the surface is interactive",
      },
    ],
  },
  {
    path: "switch",
    name: "Switch",
    description: "A switch component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-switch",
      "@/utils/cn",
    ],
    exports: ["Switch"],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper"],
        defaultValue: "paper",
        description: "The material of the switch",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", ...allSchemes],
        defaultValue: "default",
        description: "The color scheme of the switch",
      },
    ],
  },
  {
    path: "tabs",
    name: "Tabs",
    description: "A tabs component",
    dependencies: [
      "react",
      "class-variance-authority",
      "react-aria-components",
      "@/utils/cn",
    ],
    exports: ["Tabs", "TabList", "TabPanel", "Tab"],
    props: [
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: allSchemes,
        defaultValue: "primary",
        description: "The color scheme of the tabs",
      },
      {
        prop: "size",
        label: "Size",
        type: "toggle-group",
        options: ["sm", "md", "lg"],
        defaultValue: "md",
        description: "The size of the tabs",
      },
    ],
  },
  {
    path: "toggle-group",
    name: "ToggleGroup",
    description: "A toggle group component",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-toggle-group",
      "@/utils/cn",
    ],
    exports: ["ToggleGroup", "ToggleGroupItem"],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper"],
        defaultValue: "paper",
        description: "The material of the toggle group",
      },
      {
        prop: "size",
        label: "Size",
        type: "toggle-group",
        options: ["sm", "md", "lg"],
        defaultValue: "md",
        description: "The size of the toggle group",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: allSchemes,
        defaultValue: "primary",
        description: "The color scheme of the toggle group",
      },
    ],
  },
  {
    path: "alert",
    name: "Alert",
    description: "Displays a callout for user attention",
    dependencies: ["react", "class-variance-authority", "@/utils/cn"],
    exports: ["Alert", "AlertTitle", "AlertDescription"],
    props: [
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", "muted", "good", "caution", "bad"],
        defaultValue: "default",
        description: "The color scheme of the alert",
      },
    ],
  },
  {
    path: "alert-dialog",
    name: "AlertDialog",
    description: "A modal dialog for important confirmations",
    dependencies: [
      "react",
      "@radix-ui/react-alert-dialog",
      "@/utils/cn",
    ],
    exports: [
      "AlertDialog",
      "AlertDialogTrigger",
      "AlertDialogContent",
      "AlertDialogHeader",
      "AlertDialogFooter",
      "AlertDialogTitle",
      "AlertDialogDescription",
      "AlertDialogAction",
      "AlertDialogCancel",
    ],
    props: [],
  },
  {
    path: "avatar",
    name: "Avatar",
    description: "An image element with a fallback for representing the user",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-avatar",
      "@/utils/cn",
    ],
    exports: ["Avatar", "AvatarImage", "AvatarFallback"],
    props: [
      {
        prop: "size",
        label: "Size",
        type: "toggle-group",
        options: ["sm", "md", "lg", "xl"],
        defaultValue: "md",
        description: "The size of the avatar",
      },
    ],
  },
  {
    path: "badge",
    name: "Badge",
    description: "Displays a badge or status indicator",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-slot",
      "@/utils/cn",
    ],
    exports: ["Badge"],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper", "outline"],
        defaultValue: "paper",
        description: "The material of the badge",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", ...allSchemes],
        defaultValue: "default",
        description: "The color scheme of the badge",
      },
    ],
  },
  {
    path: "card",
    name: "Card",
    description: "Displays a card with header, content, and footer",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-slot",
      "@/utils/cn",
    ],
    exports: [
      "Card",
      "CardHeader",
      "CardTitle",
      "CardDescription",
      "CardContent",
      "CardFooter",
    ],
    props: [
      {
        prop: "material",
        label: "Material",
        type: "toggle-group",
        options: ["paper", "glass"],
        defaultValue: "paper",
        description: "The material of the card",
      },
      {
        prop: "interactive",
        label: "Interactive",
        type: "boolean",
        description: "Whether the card is interactive",
      },
    ],
  },
  {
    path: "checkbox",
    name: "Checkbox",
    description: "A control that allows the user to toggle between checked and unchecked",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-checkbox",
      "@/utils/cn",
    ],
    exports: ["Checkbox"],
    props: [
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", "primary", "secondary", "tertiary", "good", "caution", "bad"],
        defaultValue: "default",
        description: "The color scheme of the checkbox",
      },
    ],
  },
  {
    path: "collapsible",
    name: "Collapsible",
    description: "An interactive component which expands/collapses content",
    dependencies: ["react", "@radix-ui/react-collapsible"],
    exports: ["Collapsible", "CollapsibleTrigger", "CollapsibleContent"],
    props: [],
  },
  {
    path: "context-menu",
    name: "ContextMenu",
    description: "Displays a menu triggered by right-click",
    dependencies: [
      "react",
      "@radix-ui/react-context-menu",
      "@/utils/cn",
    ],
    exports: [
      "ContextMenu",
      "ContextMenuTrigger",
      "ContextMenuContent",
      "ContextMenuItem",
      "ContextMenuCheckboxItem",
      "ContextMenuRadioItem",
      "ContextMenuLabel",
      "ContextMenuSeparator",
      "ContextMenuShortcut",
      "ContextMenuGroup",
      "ContextMenuSub",
      "ContextMenuSubContent",
      "ContextMenuSubTrigger",
      "ContextMenuRadioGroup",
    ],
    props: [],
  },
  {
    path: "hover-card",
    name: "HoverCard",
    description: "For sighted users to preview content available behind a link",
    dependencies: [
      "react",
      "@radix-ui/react-hover-card",
      "@/utils/cn",
    ],
    exports: ["HoverCard", "HoverCardTrigger", "HoverCardContent"],
    props: [],
  },
  {
    path: "progress",
    name: "Progress",
    description: "Displays an indicator showing the completion progress of a task",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-progress",
      "@/utils/cn",
    ],
    exports: ["Progress"],
    props: [
      {
        prop: "value",
        label: "Value",
        type: "number",
        defaultValue: 50,
        description: "The progress value (0-100)",
      },
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", "primary", "secondary", "tertiary", "good", "caution", "bad"],
        defaultValue: "default",
        description: "The color scheme of the progress bar",
      },
    ],
  },
  {
    path: "radio",
    name: "RadioGroup",
    description: "A set of checkable buttons where only one can be checked at a time",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-radio-group",
      "@/utils/cn",
    ],
    exports: ["RadioGroup", "RadioGroupItem"],
    props: [
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", "primary", "secondary", "tertiary", "good", "caution", "bad"],
        defaultValue: "default",
        description: "The color scheme of the radio group",
      },
    ],
  },
  {
    path: "skeleton",
    name: "Skeleton",
    description: "Used to show a placeholder while content is loading",
    dependencies: ["react", "@/utils/cn"],
    exports: ["Skeleton"],
    props: [],
  },
  {
    path: "table",
    name: "Table",
    description: "A responsive table component",
    dependencies: ["react", "@/utils/cn"],
    exports: [
      "Table",
      "TableHeader",
      "TableBody",
      "TableFooter",
      "TableHead",
      "TableRow",
      "TableCell",
      "TableCaption",
    ],
    props: [],
  },
  {
    path: "toast",
    name: "Toast",
    description: "A succinct message that is displayed temporarily",
    dependencies: [
      "react",
      "class-variance-authority",
      "@radix-ui/react-toast",
      "@/utils/cn",
    ],
    exports: [
      "ToastProvider",
      "ToastViewport",
      "Toast",
      "ToastTitle",
      "ToastDescription",
      "ToastClose",
      "ToastAction",
    ],
    props: [
      {
        prop: "scheme",
        label: "Scheme",
        type: "select",
        options: ["default", "good", "caution", "bad"],
        defaultValue: "default",
        description: "The color scheme of the toast",
      },
    ],
  },
  {
    path: "tooltip",
    name: "Tooltip",
    description: "A popup that displays information related to an element when hovered",
    dependencies: [
      "react",
      "@radix-ui/react-tooltip",
      "@/utils/cn",
    ],
    exports: [
      "Tooltip",
      "TooltipTrigger",
      "TooltipContent",
      "TooltipProvider",
      "TooltipArrow",
    ],
    props: [],
  },
  {
    path: "dropdown-menu",
    name: "DropdownMenu",
    description: "Displays a menu of actions triggered by a button",
    dependencies: [
      "react",
      "@radix-ui/react-dropdown-menu",
      "@/utils/cn",
    ],
    exports: [
      "DropdownMenu",
      "DropdownMenuTrigger",
      "DropdownMenuContent",
      "DropdownMenuItem",
      "DropdownMenuCheckboxItem",
      "DropdownMenuRadioItem",
      "DropdownMenuLabel",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuGroup",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuRadioGroup",
      "DropdownMenuPortal",
    ],
    props: [],
  },
  {
    path: "scroll-area",
    name: "ScrollArea",
    description: "Augments native scroll functionality with custom styling",
    dependencies: [
      "react",
      "@radix-ui/react-scroll-area",
      "@/utils/cn",
    ],
    exports: ["ScrollArea", "ScrollBar"],
    props: [],
  },
  {
    path: "color-picker",
    name: "ColorPicker",
    description: "A color picker with area, sliders, and swatches",
    dependencies: [
      "react",
      "class-variance-authority",
      "react-aria-components",
      "@/utils/cn",
    ],
    exports: [
      "ColorPicker",
      "ColorSwatch",
      "ColorArea",
      "ColorSlider",
      "ColorField",
      "ColorSwatchPicker",
      "ColorSwatchPickerItem",
      "parseColor",
    ],
    props: [],
  },
];
