name: Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: prj_ks08sdZrKji4i2bkasWDri5t65GS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/web-docs/**/*

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Regenerate node_modules from cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-install-${{ hashFiles('**/bun.lockb') }}

      - name: Install project dependencies
        run: bun install --immutable

      - name: Deploy web docs
        run: bun run --cwd apps/web-docs deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
