name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.18"
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run --cwd packages/earthling-ui build

      - name: Publish to npm
        run: npm publish -w earthling-ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
